### ISSUE TITLE
rosnode working example

### ISSUE THREAD

**Issue by fmros** [ScalABLE40/robin#8]
Hy,

thank you for your great contribution! Could you provide a working example as seen in this video: https://www.youtube.com/watch?time_continue=257&v=TKU9vKwQCX8&feature=emb_logo at minute 4:36 for the usage of ROBIN inside an example application?
Is there a example arround already?

Thank you!

**Comment by henriquedomingos** [comment]
Hi,

Thank you on behalf of all the team members.
We do have an example that is explored in the [Usage](https://github.com/ScalABLE40/robin#usage) section of our README that is shown in the [Examples](https://github.com/ScalABLE40/robin#usage) section. It is an _xml_ file that can be imported to the CODESYS and then used to generate the C++ code that supports the shared memory mechanism.
Do you need any specific help in achieving some behavior?
