### ISSUE TITLE
Issues on Raspberry Pi 3

### ISSUE THREAD

**Issue by dbubalik** [ScalABLE40/robin#9]
Hi,

I am currently trying to get this to work on a Raspberry Pi 3 with Raspbian Buster for a project at the institute i am working at. This is my first time working with ROS, so after having some issues actually getting ROS on the Raspberry Pi i managed to successfully install Kinetic on it. For that i followed [these ](http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Kinetic%20on%20the%20Raspberry%20Pi) instructions using the ROS-Comm variant. One question right away: is it correct to create a new catkin workspace as per your installation instructions besides the one created during the initial installation of ROS Kinetic (ros_catkin_ws)?

My first issue: arriving at step 4 of the installation instructions the command `rosdep install robin_updater` returns:
```
ERROR: Rosdep cannot find all required resources to answer your query
Missing resource robin_updater
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/opt/ros/kinetic/share
```
Searching on Google for a bit one suggestion was to run the source command from Step 2 again. after that the command `rosdep install robin_updater` returns: 
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
robin_updater: No definition of [rostest] for OS [debian]
```
Consulting Google once again suggested adding `--os=debian:buster` to the command, however the same error is returned. I resorted to just skipping this command and continuing with step 5. This returned no errors so i proceeded to the Usage section.

(this is just a minor issue) At step 4 (running the updater application) when the command prompt opens and requests the password again i have to type it in 3 times until it finally accepts it. The updater finishes successfully with the following output:

```
* * * * * * * * * * * * *
* * * Robin Updater * * *
* * * * * * * * * * * * *

Creating SSH key ...

Adding SSH key to agent ...
Error connecting to agent: No such file or directory

Adding SSH key to target ... Password will be required
pi@raspberrypi's password:
touch: cannot touch '/home/pi/.ssh/authorized_keys': Permission denied
Accessing target through ssh... Ensure ssh service is ON. 
Connecting... 
pi@raspberrypi's password: 
pi@raspberrypi's password:

Generating source code...

Generating new ros package robin_bridge_generated...

Recompiling...

Restarting...
ROS master is not running.

Update finished.
```

Continuing to Step 5, the command `roslaunch robin_bridge_generated run.launch` returns:
`[run.launch] is neither a launch file in package [robin_bridge_generated] nor is [robin_bridge_generated] a launch file name
The traceback for the exception was written to the log file`
Running the alternative command `rosrun robin_bridge_generated robin_node_generated` yields
`[rospack] Error: package 'robin_bridge_generated' not found`
Once again searching for a bit on Google suggested running the source command from Step 2 again. Running `roslaunch robin_bridge_generated run.launch` now yields:
```
... logging to /home/pi/.ros/log/643f17c2-f406-11ea-a6ff-b827ebe9bd6e/roslaunch-raspberrypi-1701.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://raspberrypi:40893/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.16

NODES
  /
    robin_bridge_generated (robin_bridge_generated/run.sh)

auto-starting new master
process[master]: started with pid [1711]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 643f17c2-f406-11ea-a6ff-b827ebe9bd6e
process[rosout-1]: started with pid [1724]
started core service [/rosout]
process[robin_bridge_generated-2]: started with pid [1727]

[ INFO]: Stopping codesyscontrol service ... Trying with systemctl

[ INFO]: Starting codesyscontrol service via systemctl

[ INFO]: Starting robin bridge ...


[rosrun] Couldn't find executable named robin_node_generated below /home/pi/catkin_ws/src/robin_bridge_generated
[robin_bridge_generated-2] process has died [pid 1727, exit code 3, cmd /home/pi/catkin_ws/src/robin_bridge_generated/launch/run.sh __name:=robin_bridge_generated __log:=/home/pi/.ros/log/643f17c2-f406-11ea-a6ff-b827ebe9bd6e/robin_bridge_generated-2.log].
log file: /home/pi/.ros/log/643f17c2-f406-11ea-a6ff-b827ebe9bd6e/robin_bridge_generated-2*.log
```

This is as far as i could go through the installation/usage with my very limited knowledge of ROS. I would appreciate it alot if you can help me resolve these problems.

Kind regards
Daniel

**Comment by dbubalik** [comment]
I have attempted to install this ROS package again. This time i used a fresh raspbian where i also managed to install ros melodic without any issues. once again i got stuck at `rosdep install robin_updater`. Once again i received 
```
ERROR: Rosdep cannot find all required resources to answer your query
Missing resource robin_updater
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/opt/ros/kinetic/share 
```
I used the source command as before, ran the rosdep command again and this time received
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
robin_updater: No definition of [rostest] for OS version [buster]
```
running `rosdep resolve rostest` gives
```
ERROR: No definition of [rostest] for OS version [buster]

No definition of [rostest] for OS version [buster]
        rosdep key : rostest
        OS name    : debian
        OS version : buster
        Data:
_is_ros: true
                debian:
                  stretch:
                    apt:
                      packages:
                      - ros-melodic-rostest
                osx:
                  homebrew:
                    packages:
                    - ros/melodic/ros_comm
                ubuntu:
                  bionic:
                    apt:
                      packages:
                      - ros-melodic-rostest
```
So again i added `--os=debian:stretch´ to the command (this time with stretch instead of buster as in my original post) and get
```
executing command [sudo -H apt-get install ros-melodic-catkin]
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ros-melodic-catkin
ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install ros-melodic-catkin] failed
```
again this is as far as i can get. i would really appreciate any help on this issue.

edit: tried `rosdep resolve rostest` on the raspbian image that has ros kinetic: 

```
ERROR: No definition of [rostest] for OS [debian]

No definition of [rostest] for OS [debian]
        rosdep key : rostest
        OS name    : debian
        OS version : buster
        Data:
_is_ros: true
                osx:
                  homebrew:
                    packages:
                    - ros/kinetic/ros_comm
                ubuntu:
                  xenial:
                    apt:
                      packages:
                      - ros-kinetic-rostest
```

the difference here is, that it does not list debian like in the melodic installation, so i just tried running `rosdep install robin_updater` with optional argument --os=ubuntu:xenial, however the same error is returned (with melodic being replaced by kinetic)

**Comment by henriquedomingos** [comment]
Hi,

Regarding the workspaces, for now, to avoid any complications you should only use one. Make sure this workspace is correctly sourced in your _.bashrc_ file as recommended in the ROSTutorials.

`source /opt/ros/melodic/setup.bash`
`source ~/<workspace_name>/devel/setup.bash`

I would advise you to manually change the _package.xml_ file inside the _robin_updater_ package. For debian I believe you should replace _rostest_ for _python-rostest_ and try again.

See if it works and sorry for the late reply.

**Comment by dbubalik** [comment]
Unfortunately your suggestions do not seem to work. This is basically where i am at right now:
I have installed ROS Melodic according to [these](http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Melodic%20on%20the%20Raspberry%20Pi) instructions. During the installation a catkin workspace is created (ros_catkin_ws, step 3.1). 
first thing i have now tried:
I have cloned the robin repository into the src folder inside ros_catkin_ws, thus skipping step 2 of the robin package installation (because i already have a catkin workspace ros_catkin_ws). 
Now i run rosdep install robin_updater:
```
ERROR: Rosdep cannot find all required resources to answer your query
Missing resource robin_updater
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/opt/ros/melodic/share
```
During the installation of ros melodic `source /opt/ros/melodic/setup.bash` has been added to the .bashrc file. The directory of the workspace looks like 
`build_isolated  devel_isolated  melodic-ros_comm-wet.rosinstall  src`.
Since there is no _devel_ folder i source the _setup.bash_ inside _devel_isolated_ `source ~/ros_catkin_ws/devel_isolated/setup.bash`  and then run `rosdep install robin_updater` i receive 
```
ERROR: Rosdep cannot find all required resources to answer your query
Missing resource robin_updater
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/pi/ros_catkin_ws/src/ros_comm/roswtf
ROS path [2]=/opt/ros/melodic/share
```
second thing i have tried:
In the melodic installation instructions the initial workspace ros_catkin_ws is used to build the core packages. i assume this workspace should then not be use to work in/from. So, following the robin installation instructions, i create a new workspace to work from, and arrive at step. 4: running `rosdep install robin_updater` with the response:
```
ERROR: Rosdep cannot find all required resources to answer your query
Missing resource robin_updater
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/opt/ros/melodic/share
```
i run `source ~/catkin_ws/devel/setup.bash` and then use `echo $ROS_PACKAGE_PATH` to check:`
/home/pi/catkin_ws/src:/home/pi/ros_catkin_ws/src/ros_comm/roswtf:/opt/ros/melodic/share`
i run `rosdep install robin_updater`:
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
robin_updater: No definition of [rostest] for OS version [buster]
```
i go into _package.xml_ and replace _rostest_ with _python-rostest_, and then run `rosdep install robin_updater`:
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
robin_updater: Cannot locate rosdep definition for [python-rostest]
```
Maybe there is something i am missing/skipping or simply not understanding. can you quickly outline how to install/setup the robin package on a fresh, new raspbian image with nothing else installed? (so: install ros melodic or kinetic according to installation instructions, etc...)

edit: looking at the ros/installation page, kinetic lists debian jessie, melodic lists debian stretch, and noetic lists debian buster. maybe the reason for the error `robin_updater: No definition of [rostest] for OS version [buster]` is, that i am trying to use melodic on debian buster? as described in a previous comment, adding `--os=debian:stretch` to the command leads to:
```
executing command [sudo -H apt-get install ros-melodic-catkin]
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ros-melodic-catkin
ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install ros-melodic-catkin] failed
```

**Comment by henriquedomingos** [comment]
Using ROS melodic with Debian buster may well be the cause of those problems. Please try using ROS melodic and Debian stretch.
Note that, as expressed in the documentation, the robin package was not yet tested in Debian but we believe it shouldn't make any difference.

We look forward to hear from you.

**Comment by dbubalik** [comment]
installed raspbian stretch from [here](http://downloads.raspberrypi.org/raspbian/images/raspbian-2019-04-09/). Installed ROS Melodic, no issues. Arriving at `rosdep install robin_updater` (no additional arguments):
 ```
executing command [sudo -H apt-get install ros-melodic-catkin]
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ros-melodic-catkin
ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install ros-melodic-catkin] failed
```

I also considered just installing ubuntu 18.04 on the Pi and then getting _CODESYS Control for Linux SL_, however that requires hardware with x86 architecture. The Pi unfortunately is an arm architecture. I have also seen mention of _CODESYS Control for Linux Arm SL_ (for example in the codesys online [help](https://help.codesys.com/webapp/_lnxarm_f_help;product=codesys_control_for_linux_arm_sl;version=3.5.16.0)), however this doesn't seem to be available in the CODESYS Store yet. Do you perhaps have any information regarding that?

**Comment by henriquedomingos** [comment]
I tried to replicate the process using a Docker image of debian:stretch. The installation completed without any problems following the standard procedure explained in the README file. Currently, we have no way of testing _robin_ in a real Raspberry Pi.

**Nonetheless, I have a few suggestions:**

1. With the installation that you have done following [this](http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Melodic%20on%20the%20Raspberry%20Pi), instead of running `rosdep install robin_updater` please run this `rosdep install -y --from-paths src --ignore-src --rosdistro melodic -r --os=debian:buster` **inside your workspace**. **Use only one workspace** correctly sourced inside _~/.bashrc_ file. **If the problem persists** (failing to install _rostest_) try installing the required libraries manually through _pip_ or _apt-get_.

2. **If your Pi is compatible** (starting at version 2) try using Ubuntu Mate as explained in [here](http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Melodic%20on%20the%20Raspberry%20Pi) and [here](https://roboticsbackend.com/install-ubuntu-mate-18-04-on-raspberry-pi-3-b/).

3. **Have you considered / is it possible for you to use another device?** We have successfully used Beaglebone Black running Ubuntu (both with ROS kinetic and melodic) which also allows to use the free _CODESYS Control for Linux SL_.

Regarding the _CODESYS Control for Linux Arm SL_ I have seen in the store has a [version](https://store.codesys.com/codesys-control-for-raspberry-pi-sl.html?___store=en) for Raspberry Pi which might be suitable for your requirements.

**Comment by dbubalik** [comment]
we have now successfully installed Ubuntu Server 18.0.4.5 (armhf), ROS Melodic, Codesys Control for Raspberry Pi SL and the robin Bridge, all without any additional/optional arguments or errors. However the very last step under the Usage section fails (updater application script finishes successfully) with the following output:
```
ubuntu@ubuntu:~$ roslaunch robin_bridge_generated run.launch
... logging to /home/ubuntu/.ros/log/5f41b772-0d45-11eb-93a3-b827ebbce83b/roslaunch-ubuntu-2104.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:40567/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.9

NODES
  /
    robin_bridge_generated (robin_bridge_generated/run.sh)

auto-starting new master
process[master]: started with pid [2115]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 5f41b772-0d45-11eb-93a3-b827ebbce83b
process[rosout-1]: started with pid [2126]
started core service [/rosout]
process[robin_bridge_generated-2]: started with pid [2129]

[ INFO]: Stopping codesyscontrol service ... Trying with systemctl

[ INFO]: Starting codesyscontrol service via systemctl

[ INFO]: Starting robin bridge ...

[rosrun] Couldn't find executable named robin_node_generated below /home/ubuntu/catkin_ws/src/robin_bridge_generated
[robin_bridge_generated-2] process has died [pid 2129, exit code 3, cmd /home/ubuntu/catkin_ws/src/robin_bridge_generated/launch/run.sh __name:=robin_bridge_generated __log:=/home/ubuntu/.ros/log/5f41b772-0d45-11eb-93a3-b827ebbce83b/robin_bridge_generated-2.log].
log file: /home/ubuntu/.ros/log/5f41b772-0d45-11eb-93a3-b827ebbce83b/robin_bridge_generated-2*.log
```
looking at one of the logs created _~/.ros/log/5f41b772-0d45-11eb-93a3-b827ebbce83b/roslaunch-ubuntu-2104.log_ (the log mentioned a few lines above does not seem to exist) i see this section
```
[roslaunch][INFO] 2020-10-13 13:15:21,039: ... successfully launched [robin_bridge_generated-2]
[roslaunch][INFO] 2020-10-13 13:15:21,040: ... launch_nodes complete
[roslaunch.pmon][INFO] 2020-10-13 13:15:21,041: registrations completed <ProcessMonitor(ProcessMonitor-1, started daemon -1241373600)>
[roslaunch.parent][INFO] 2020-10-13 13:15:21,041: ... roslaunch parent running, waiting for process exit
[roslaunch][INFO] 2020-10-13 13:15:21,042: spin
[roslaunch][ERROR] 2020-10-13 13:15:37,532: [robin_bridge_generated-2] process has died [pid 2129, exit code 3, cmd /home/ubuntu/catkin_ws/src/robin_bridge_generated/launch/run.sh __name:=robin_bridge_generated __log:=/home/ubuntu/.ros/$log file: /home/ubuntu/.ros/log/5f41b772-0d45-11eb-93a3-b827ebbce83b/robin_bridge_generated-2*.log
```
maybe this can help with nailing down this issue. 

As a side note, i suspect the reason, why the installation does not work properly on a simple raspberry pi with raspbian is, that raspbian is based on a 32-bit debian OS (specifically armhf). looking at the ros melodic installation page it lists only arm64 and amd64 for a debian OS, whereas for ubuntu it lists amd64, armhf and arm64.

**Comment by henriquedomingos** [comment]
Please check a few things:

1. It should not be necessary, but did you **compiled everything again after running the generation mechanism** through _CODESYS IDE_? If not, please try it and run again.
2. **Have your sourced your workspace** using the command `/home/ubuntu/catkin_ws/devel/setup.bash` ?
3. Do you have a _robin_node.cpp_ inside the **_robin_bridge_generated/src_** folder?

**Comment by dbubalik** [comment]
Success!
Regarding 2. and 3., the workspace is correctly sourced (both `/opt/ros/melodic/share` and `/catkin_ws` are sourced in `~/.bashrc`), and _robin_node.cpp_ is present in `robin_bridge_generated/src`.
Compiling the workspace again after running the updater application script with catkin_make while inside /catkin_ws did the trick.
Now i can continue with creating my final application programm. If any further problems arise i will message you again. But for now I thank you very much for your time and patience with helping me. I believe this project is going to be a major contribution to automation industry. Cheers!
